package wordlist

// Animals provides a wordlist with common and uncommon singular animal names.
var Animals = []string{
	"apes", "animals", "bars", "baths", "breads", "bushes", "cloths", "clubs", "hoops", "loops", "memes", "papers", "parks", "paths", "showers", "signs", "sites", "streets", "teeth", "tires", "webs", "actors", "ads", "adults", "aliens", "ants", "apples", "apricots", "avocados", "baboons", "badgers", "bags", "balloons", "bananas", "bats", "beans", "bears", "beds", "beers", "bees", "berries", "bikes", "birds", "boats", "bobcats", "books", "bottles", "boxes", "brooms", "buckets", "bugs", "bulldogs", "buses", "buttons", "camels", "cameras", "candies", "candles", "carpets", "carrots", "cars", "cats", "chairs", "cheetahs", "chefs", "cherries", "chicken", "clocks", "clouds", "coats", "cobras", "coins", "colts", "comics", "cooks", "cougars", "regions", "cows", "crabs", "crews", "cups", "cycles", "dancers", "days", "deers", "dingos", "dodos", "dogs", "dolls", "dolphins", "donkeys", "donuts", "doodles", "doors", "dots", "dragons", "drinks", "dryers", "ducks", "eagles", "ears", "eels", "eggs", "mammals", "emus", "experts", "eyes", "falcons", "fans", "feet", "files", "fireants", "fishes", "flies", "flowers", "forks", "foxes", "friends", "frogs", "games", "garlics", "geckos", "geese", "ghosts", "gifts", "glasses", "goats", "gorillas", "grapes", "guests", "hairs", "hats", "hornets", "horses", "hotels", "hounds", "houses", "humans", "icons", "impalas", "insects", "islands", "items", "jars", "jeans", "jobs", "jokes", "angaroos", "keys", "kids", "kings", "kiwis", "knives", "ladybugs", "lamps", "laws", "lemons", "lies", "ligers", "lions", "lizards", "llamas", "lobsters", "mails", "mangos", "maps", "masks", "mayflies", "meals", "melons", "mice", "mirrors", "moles", "monkeys", "months", "moons", "moose", "mugs", "nails", "needles", "news", "numbers", "olives", "onions", "oranges", "otters", "owls", "pandas", "pans", "panthers", "pants", "papayas", "parents", "parrots", "paws", "peaches", "pears", "peas", "penguins", "pens", "pets", "phones", "pianos", "pigs", "pillows", "planes", "planets", "plants", "plums", "poems", "poets", "points", "pots", "pugs", "pumas", "pumpkins", "queens", "rabbits", "radios", "rats", "ravens", "readers", "rice", "rings", "rivers", "rockets", "rocks", "roses", "rules", "schools", "scissors", "seals", "seas", "sheep", "shirts", "shoes", "shrimps", "singers", "sloths", "snails", "snakes", "socks", "spiders", "spies", "spoons", "squids", "stars", "steaks", "wings", "students", "suits", "suns", "swans", "symbols", "tables", "taxis", "teachers", "terms", "ties", "tigers", "timers", "tips", "toes", "tomatoes", "tools", "toys", "trainers", "trains", "trams", "trees", "turkeys", "turtles", "vans", "walls", "wasps", "waves", "ways", "weeks", "windows", "wolves", "wombats", "worms", "yaks", "years", "zebras", "zoos",
}

// var Animal = map[string][]string{
// 	"adjectives": {},
// 	"nouns":      {},
// }
