name: go

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.12", "1.13", "1.14", "1.15", "1.16"]

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2.1.7
        with:
          path: ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-
      - name: Test
        run: go test -coverprofile=profile.cov ./...
      - name: Send coverage
        if: matrix.go == '1.16'
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
